name: 'Amazon Events "Render Targets Definition" Action for GitHub Actions'
description: 'Inserts a task definition URI into a target definition in an Amazon Events target definition JSON file, creating a new file.'
branding:
  icon: 'cloud'
  color: 'orange'
inputs:
  targets-definition:
    description: 'The path to the Events targets definition JSON file'
    required: true
  task-definition-arn:
    description: 'The ARN of the task definition to inserty into the Events targest definition'
    required: true
outputs:
  targets-definition:
    description: 'The path to the rendered targets definition file'
runs:
  using: 'node16'
  main: 'dist/index.js'